### ISSUE TITLE
Buffer() is now deprecated.

### ISSUE THREAD

**Issue by shortthefomo** [professorhantzen/ripple-secret-codec#1]
https://github.com/professorhantzen/ripple-secret-codec/blob/419637066830a1bc45473b5f189a26cf89547cd4/ripple-secret-codec.js#L17

After chasing this one around a few libs finally found the source of this. 
https://github.com/WietseWind/xrpl-accountlib/issues/308 (original issue)
https://github.com/HotPocketDev/evernode-sdk/issues/35

Buffer() is now deprecated. 

xrpl-accountlib is one of the libraries I use consistently that implements this codec.

**Comment by WietseWind** [comment]
https://github.com/WietseWind/xrpl-accountlib/issues/308#issuecomment-1284585280
